### ISSUE TITLE
Criar o código HTML baseado no layout do UX/UI

### ISSUE THREAD

**Issue by danvitoriano** [danvitoriano/minhas-financas#1]
Layout da aplicação a ser feita:
https://imgur.com/xJp6XB2
![Screen Shot 2020-04-01 at 12 27 07 PM](https://user-images.githubusercontent.com/3236750/78199631-a742a080-7462-11ea-9322-ef1099fb8056.png)

**Comment by danvitoriano** [comment]
TENHO INTERESSE EM ASSUMIR ESTA ISSU

**Comment by fwfcunha** [comment]
teste

**Comment by rafaelcaldastx** [comment]
Tenho interesse nessa issue! 
Rafael Caldas 336323

**Comment by deciomontanhani** [comment]
Tenho interesse!

**Comment by GAPvox** [comment]
teste

**Comment by asnisapps** [comment]
Opa

**Comment by juniorstaudt** [comment]
Tenho interesse na issue (Junior Staudt)

**Comment by RogerPhilippe** [comment]
TENHO INTERESSE EM ASSUMIR ESTA ISSUE.

**Comment by brunomcortez** [comment]
tenho interesse na issue

**Comment by PlantierBruna** [comment]
Tenho interesse em assumir a issue

**Comment by VitorFerraz** [comment]
TENHO INTERESSE EM ASSUMIR ESTA ISSU

**Comment by victorhossepian** [comment]
Victor Hossepian 336860

**Comment by costatatiane** [comment]
Interesse!

**Comment by cunhaguilherme** [comment]
Tenho interesse!
