### ISSUE TITLE
💥 [OPEN SOURCE] - Ordenar Lista de Finanças

### ISSUE THREAD

**Issue by danvitoriano** [danvitoriano/minhas-financas#32]
# Ordenar Lista de Finanças 

Nossa aplicação é capaz de exibir uma lista de finanças em uma tabela, que pode ser alimentada pelo usuário ou importada de serviços na web. Para deixarmos a aplicação ainda melhor, que tal permitir que o usuário ordene a tabela, clicando em cada coluna?

Por exemplo, se o usuário clicar na coluna "QUANTIDADE", ordenaremos pela quantidade, se ele clicar na coluna "DATA", ordenaremos pela data. Além disso, se ele clicar mais de uma vez na mesma coluna, ele ordenará a tabela ascendentemente ou descendentemente. 

A primeira coisa a fazer é criar um método em `FinancaController`, que será o responsável em ordenar a `ListaFinancas`. A ordenação da lista envolve sua alteração, logo, a view `FinancasView` precisará ser atualizada. 

Altere /controllers/FinancaController.js e adicione o método ordena:

```js
ordena(coluna) {
    // ainda vamos implementar o método!
}
```

Veja que o método ordena recebe como parâmetro a coluna que queremos ordenar. Lembre-se que ordenaremos nosso modelo pela coluna que o usuário clicar, sendo assim, nada mais justo do que associar o método ordena ao evento click do cabeçalho de cada coluna em /views/FinancasView.js:

```js
<thead>
    <tr>
        <th onclick="financaController.ordena('data')">ITEM</th>
        <th onclick="financaController.ordena('data')">DATA</th>
        <th onclick="financaController.ordena('quantidade')">#</th>
        <th onclick="financaController.ordena('valor')">$</th>
        <th>=</th>
    </tr>
</thead>
```

Obs.: não é necessário ordenar pela coluna de total (=).

Quando associamos a chamada do método ao evento, passamos como parâmetro do método a coluna que desejamos ordenar. É importante que cada parâmetro passado exista como uma propriedade em nosso modelo `Financa`.

Cada finança da lista é uma instância da classe `Financa`. Primeiramente, implemente a solução de ordenação sem se preocupar em alternar ascendentemente ou descendentemente. Entenda como é feito o processo de ordenação de uma lista a partir de algum critério lendo o post no Medium "[**Ordenando listas com JavaScript Array.sort**](https://medium.com/@dnvtrn/ordenando-listas-com-javascript-array-sort-52446c25d94b)".

Ao acessarmos `this.listaFinancas.financas` recebemos uma cópia da lista original. Qualquer alteração na lista não afeta a instância de `ListaFinancas`. Para resolvermos isso, precisamos criar o método **ordena** em `models/ListaFinancas.js`. Este método receberá o critério de ordenação, que será passado para a lista de finanças encapsulada pela classe:

```js
class ListaFinancas {
    ordena(criterio) {
        this.financas.sort(criterio);        
    }
}
```

Agora, vamos voltar para FinancaController e alterar seu método ordena e implementá-lo:

```js
class FinancaController {
    ordena(coluna) {
        this.listaFinancas.ordena((a, b) => a[coluna] - b[coluna]);    
    }
}
```

Usamos a sintaxe objeto[nomePropriedade] para acessar a propriedade do objeto. Essa forma mais verbosa é interessante quando queremos acessar as propriedades de um objeto dinamicamente.

Precisamos atualizar a view quando o método ordena do nosso modelo for chamado. Para isso, precisamos adicioná-lo na lista de métodos ou propriedades que desejamos monitorar do nosso modelo.

Faça um teste agora. Alterne cliques em algumas colunas e veja o resultado. 

Precisamos agora efetuar uma ordenação ascendente ou descendente quando o usuário clicar na mesma coluna. Se a ordenação atual é X e ele clicou em outra coluna, trocando a ordenação para Y, não fazemos nada e deixamos a lista ser ordenada por Y. No entanto, se a ordenação atual é X e ele clica na coluna que solicita novamente uma ordenação por X, invertemos a ordem atual. Crie como propriedade de `FinancaController` no construtor a propriedade `this.ordemAtual`. Quando a página for carregada, não tem critério, ou seja, a propriedade recebe uma string vazia. Só passa a ter quando alguém começa a clicar nas colunas. Aplica no método `ordena`, uma condicional `if` que verifica se `this.ordemAtual` é igual a coluna clicada. 
 
Para invertermos a lista, precisamos criar em `models/ListaFinancas.js` o método `inverteOrdem`, que chama `this.financas.reverse()` para nós.

Agora, podemos adicione a chamada do `inverteOrdem` na nossa controller com esta última alteração.
Não podemos nos esquecer de adicionar o método `inverteOrdem` como um dos métodos que estamos monitorando para atualizar a View.

Experimente agora brincar com os critérios de ordenação clicando nos cabeçalhos das colunas da nossa tabela.

****

> ### IMPORTANTE
> - Para assumir esta _issue_, comente aqui seu interesse com nome e RM. O limite de pessoas responsáveis por uma _issue_ é de no máximo 4 usuários. Os 4 primeiros a demonstrar interesse serão automaticamente "_Assigned_" para _issue_ formando um grupo responsável por resolvê-la e gerenciar a discussão nos comentários.
> - Verifique se esta _issue_ possui relação e dependência com outras _issues_. Você provavelmente vai precisar conversar através dos comentários e de maneira pública com os responsáveis pelas _issues_ relacionadas.
> - Não esqueça de sempre buscar a atualização mais recente da branch `master` do repositório `upstream` e mesclá-la com a branch da sua _issue_.
> - Resolva os conflitos caso hajam.
> - Caso ao abrir sua _Pull Request_ apareça a mensagem _Can't automatically merge_, verifique se um novo código já foi mesclado na `master` entre o período que você finalizou suas alterações locais até o momento da abertura de solicitação do _Code Review_. Caso isso aconteça, você precisará atualizar seu código local e repetir a abertura da sua solicitação.
> - Para mais informações sobre repositórios `upstream`, `git pull`, `git push`, `git merge` e abertura de _Pull Requests_, consulte a Ajuda na nossa Wiki.

**Comment by juniorstaudt** [comment]
Junior Mauricio Staudt
RM336234

**Comment by VitorFerraz** [comment]
Tenho interesse na issue
Vitor Ferraz Varela - RM336042

**Comment by brunomcortez** [comment]
tenho interesse nessa issue
Bruno M Cortez - RM335963

**Comment by xudre** [comment]
![precious](https://user-images.githubusercontent.com/1762533/79245866-151d9d80-7e4f-11ea-973d-1c42e8625a2d.gif)
Choose me...
Pedro Xudre - RM336544

**Comment by deciomontanhani** [comment]
Tenho interesse!!!!
Décio Montanhani - RM336080
