### ISSUE TITLE
💥 [OPEN SOURCE] - Filtrar Finanças por Data

### ISSUE THREAD

**Issue by danvitoriano** [danvitoriano/minhas-financas#33]
# Filtrar Finanças por Data

Nossa aplicação exibe uma lista com todas as finanças criadas e importadas. Porém, com o crescimento desta lista, fica cada vez mais difícil encontrar uma determinada finança. Seria interessante termos um campo onde fosse possível filtrar todas as finanças e listar apenas aquelas que são de nosso interesse.

O método `filter()` do JavaScript cria um novo array com todos os elementos que passaram no filtro implementado pela função fornecida. Ex.:

```js
function isBigEnough(value) {
  return value >= 10;
}
```

```js
var filtered = [12, 5, 8, 130, 44].filter(isBigEnough);
// filtrado é [12, 130, 44]
```

Utilizando o paradigma de programação funcional, crie um novo campo de texto ou data chamado **Filtro** e um botão **Filtrar** logo acima da nossa Lista de Finanças em `index.html` e altere o código para que controllers, modelos e as views sejam atualizadas ao aplicarmos um filtro por **Data**.

As modificações nos controllers e modelos são semelhantes ao processo proposto na _issue_ #32. Consulte para obter mais informações e lhe ajudar no seu desenvolvimento.

---

> ### IMPORTANTE
>
> - Para assumir esta _issue_, comente aqui seu interesse com nome e RM. O limite de pessoas responsáveis por uma _issue_ é de no máximo 4 usuários. Os 4 primeiros a demonstrar interesse serão automaticamente "_Assigned_" para _issue_ formando um grupo responsável por resolvê-la e gerenciar a discussão nos comentários.
> - Verifique se esta _issue_ possui relação e dependência coom outras _issues_. Você provalvelmente vai precisar conversar atraves dos comentários e de maneira pública com os reponsáveis pelas _issues_ relacionadas.
> - Não esqueça de sempre buscar a atualização mais recente da branch `master` do repositório `upstream` e mescla-lá com a branch da sua _issue_.
> - Resolva os conflitos caso hajam.
> - Caso ao abrir sua _Pull Request_ apareça a mensagem _Can't automatically merge_, verifique se um novo código já foi mesclado na `master` entre o período que você finalizou suas alterações locais até o momento da abertura de solicitação do _Code Review_. Caso isso aconteça, você precisará atualizar seu código local e repetir a abertura da sua solicitação.
> - Para mais informações sobre repositórios `upstream`, `git pull`, `git push`, `git merge` e abertura de _Pull Requests_, consulte a Ajuda na nossa Wiki.

**Comment by juniorstaudt** [comment]
Tenho interesse nessa issue
Junior Mauricio Staudt
RM336234

**Comment by LucoSPbr** [comment]
Tenho interesse nessa issue
Luiz Coaraci da Silva Campos
RM336386

**Comment by danvitoriano** [comment]
adicionado @LucoSPbr 

@LucoSPbr e @juniorstaudt se tiverem dúvidas, abram uma Pull Request com a solução, mesmo que esteja incompleta! Assim revisamos direto no código!

Tem mais gente pra entrar nesse grupo?

**Comment by juniorstaudt** [comment]
> adicionado @LucoSPbr
> 
> @LucoSPbr e @juniorstaudt se tiverem dúvidas, abram uma Pull Request com a solução, mesmo que esteja incompleta! Assim revisamos direto no código!
> 
> Tem mais gente pra entrar nesse grupo?

Olá @danvitoriano, eu fiz as inclusões do campo e do botão filtrar e queria subir, mesmo que parcialmente já para ir me acostumando com esse processo de push e pula request. Não tenho muita experiência com Git e estou tendo dificuldades para enviar minhas alterações.

Estou usando o comando git push -u origin 33 (que é a branch que eu criei para editar o index.html). O retorno é o seguinte: 
_Permission to danvitoriano/minhas-financas.git denied to juniorstaudt.
fatal: unable to access 'https://github.com/danvitoriano/minhas-financas.git/': The requested URL returned error
: 403_

Consegue me ajudar?

**Comment by juniorstaudt** [comment]
Feito pull request parcial para inclusão do campo de filtro e do botão Filtar.

**Comment by LucoSPbr** [comment]
Junior, bom dia.
Não tenho prática com o git também.. mas correndo atrás.. já forkei,
clonei, e configurei o upstrem.. gostaria de continuar/contribuir de onde
vc parou..
Como carrego as suas alterações?
Obrigado.
Luiz.

Em qui, 23 de abr de 2020 21:47, Junior Staudt <notifications@github.com>
escreveu:

**Comment by danvitoriano** [comment]
se vc forkou o repositório, vc já tem no seu código (upstream) o que temos na master (origin)

vcs já abriram um PR, e por enquanto o fluxo está correto, mais alguma dúvida @LucoSPbr ?

**Comment by juniorstaudt** [comment]
Commit da parte com o JS já foi feito, assim como a pull request. Agora aguardamos o code review do @danvitoriano para dizer se está tudo ok.

**Comment by juniorstaudt** [comment]
@LucoSPbr vou incluir a sua RM lá na entrega do trabalho, ok?!

**Comment by LucoSPbr** [comment]
> Obrigado @juniorstaudt !

**Comment by danvitoriano** [comment]
resolvido com sucesso! 👏
