### ISSUE TITLE
💥 [OPEN SOURCE] - Criar HttpService

### ISSUE THREAD

**Issue by danvitoriano** [danvitoriano/minhas-financas#34]
# Criar HttpService

O método `get` que requisita nossa API é um serviço HTTP realizado pela API de Fetch do JavaScript ES2015+. Porém, o acesso à API pode ser isolado em um serviço específico, e reutilizado tanto para uso com `get` ou outros métodos REST, como o `post`, `patch`, `put` e `delete`.

Separe a utilização do Fetch de dentro do `FinancaService` criando um novo serviço só para requisitar a Api, chamado `HttpService`.

---

> ### IMPORTANTE
>
> - Para assumir esta _issue_, comente aqui seu interesse com nome e RM. O limite de pessoas responsáveis por uma _issue_ é de no máximo 4 usuários. Os 4 primeiros a demonstrar interesse serão automaticamente "_Assigned_" para _issue_ formando um grupo responsável por resolvê-la e gerenciar a discussão nos comentários.
> - Verifique se esta _issue_ possui relação e dependência coom outras _issues_. Você provalvelmente vai precisar conversar atraves dos comentários e de maneira pública com os reponsáveis pelas _issues_ relacionadas.
> - Não esqueça de sempre buscar a atualização mais recente da branch `master` do repositório `upstream` e mescla-lá com a branch da sua _issue_.
> - Resolva os conflitos caso hajam.
> - Caso ao abrir sua _Pull Request_ apareça a mensagem _Can't automatically merge_, verifique se um novo código já foi mesclado na `master` entre o período que você finalizou suas alterações locais até o momento da abertura de solicitação do _Code Review_. Caso isso aconteça, você precisará atualizar seu código local e repetir a abertura da sua solicitação.
> - Para mais informações sobre repositórios `upstream`, `git pull`, `git push`, `git merge` e abertura de _Pull Requests_, consulte a Ajuda na nossa Wiki.

**Comment by victorhossepian** [comment]
Temos interesse nessa!! RM 336068 - Victor

**Comment by costatatiane** [comment]
Interesse! RM 336238 - Tatiane Dias Costa

**Comment by PlantierBruna** [comment]
Interesse tb RM 336456

**Comment by karlapsouza** [comment]
Tenho interesse também RM335480

**Comment by costatatiane** [comment]
<img width="420" alt="Screen Shot 2020-04-15 at 22 17 36" src="https://user-images.githubusercontent.com/40796627/79490614-8302ca00-7ff3-11ea-8b5c-55bde0727174.png">
@danvitoriano nós esboçamos duas classes de mais ou menos como seria, uma com a Promisse e outra sem. Pro nosso projeto, o melhor é fazermos esse HttpService com a Promise?

**Comment by costatatiane** [comment]
@danvitoriano Implementamos o método get do Http e está funcionando. Fomos fazer o post, mas está dando erro 404 - not found. Seria algum erro da nossa implementação ou a URL não aceita post?

**Comment by danvitoriano** [comment]
Olá @costatatiane @PlantierBruna @karlapsouza e @victorhossepian!

A primeira opção da classe de vocês está mais correta! Porém, existem alguma modificações a fazer. Onde vocês colocam a linha `.then(json => { return json})` é desnecessária. Vocês podem excluí-la e retornar diretamente o `fetch` pois o retorno dele já é o json que vocês fazem no primeiro `then`.

Sobre o 404 da API, o que acontece é que como ela está hospedada no Heroku, se ninguém a usa, o servidor entra em um estado de Stand By. É preciso abrir a URL direto no navegador, apenas para dar uma "acordada" no servidor. Peço que tentem novamente.

Outro detalhe é que para adicionar um item via post na API, vocês precisam mandar os dados iguais o que formulário envia, sem usar o `DateHelper`. Exemplo:

```js
{
    "item": "cinema",
    "data": "2020-04-14",
    "quantidade": 1,
    "valor": 450
}
```

Outra dica: ao invés de colocarem um print da dela, mandem uma **Pull Request** diretamente. Assim eu consigo comentar nas linhas que tem problemas e já resolvemos juntos o problema!

Qualquer coisa me avisem! Boa sorte!

**Comment by costatatiane** [comment]
@danvitoriano já tínhamos implementado com a Promise, podemos tirar então.
Estávamos com a API aberta no navegador, então não acredito que tenha sido esse o problema. Mas o DateHelper não tiramos, então vamos testar novamente.

Vou abrir um PR pra falarmos por lá, então!

**Comment by danvitoriano** [comment]
resolvida com sucesso
