### ISSUE TITLE
💥 [OPEN SOURCE] - Criar Helper Bind com Padrão Proxy

### ISSUE THREAD

**Issue by danvitoriano** [danvitoriano/minhas-financas#35]
# Criar Helper Bind com Padrão Proxy

Um dos padrões de projeto mais utilizados na programação é o **Proxy**. Este _design pattern_ basicamente intercepta um pedido de instanciação de um objeto inserindo funcionalidades extra ao objeto. Este objeto interceptado também é chamado de objeto encapsulado, onde o Proxy funciona como uma casca adicional ao comportamento padrão do objeto.

É muito útil quando não queremos modificar o objeto original, e mesmo assim, adicionar funcionalidades extras dependendo de cada uso.

Para entender mais sobre Proxy, leia o post no **Medium** [**Padrão de Projeto Proxy**](https://medium.com/@dnvtrn/padr%C3%A3o-de-projeto-proxy-35774727eb17)

No nosso projeto, toda vez que acionamos um método como o `adiciona`, somos obrigados a atualizar as views. Seria interessante termos mais uma classe Helper, responsável por aplicar um Proxy, toda vez que alguém chamar estes métodos, e automaticamente, atualizar as views com as modificações que o método promove.

Primeiro, crie uma classe chamada Bind.js dentro de `/helpers`. Esta classe receberá 3 parâmetros no construtor:

```js
constructor(model, view, ...props);
```

O primeiro parâmetro receberá o modelo a ser escutado pelo Proxy para que, caso haja uma atualização, a mesma propague automaticamente no segundo parâmetro, isto é, a `view` que deve ser atualizada. O terceiro e último parâmetro recebe um **Spread Operator (...)**, isto é, ele recebe uma lista de strings com o nome dos métodos que serão "interceptados" pelo Proxy. Cada um dos métodos transforma-se em novos parâmetros dentro do construtor. Para saber mais, leia o post no **Medium** [**JavaScript Spread Operator**](https://medium.com/@dnvtrn/javascript-spread-operator-17a883450f81),

A classe helper `Bind` será chamada dentro do construtor de `FinancaController`, por exemplo:

```js
this._listaFinancas = new Bind(
  new ListaFinancas(),
  new FinancasView($("#financasView")),
  "adiciona",
  "outros-métodos"
);
```

Na classe `Bind`, você precisará usar recursos de **Reflection.apply()** para que o Proxy aplique as alterações no modelo na view quando um dos métodos for interceptado. Para saber mais sobre _Reflection_ e _contexto_ no JavaScript, leia o post no **Medium** [**JavaScript Reflect.apply e o this**](https://medium.com/@dnvtrn/javascript-reflect-apply-e-o-this-4971089b35af)

Se tiver dificuldade, peça ajuda nos comentários marcando outros contribuidores.

---

> ### IMPORTANTE
>
> - Para assumir esta _issue_, comente aqui seu interesse com nome e RM. O limite de pessoas responsáveis por uma _issue_ é de no máximo 4 usuários. Os 4 primeiros a demonstrar interesse serão automaticamente "_Assigned_" para _issue_ formando um grupo responsável por resolvê-la e gerenciar a discussão nos comentários.
> - Verifique se esta _issue_ possui relação e dependência coom outras _issues_. Você provalvelmente vai precisar conversar atraves dos comentários e de maneira pública com os reponsáveis pelas _issues_ relacionadas.
> - Não esqueça de sempre buscar a atualização mais recente da branch `master` do repositório `upstream` e mescla-lá com a branch da sua _issue_.
> - Resolva os conflitos caso hajam.
> - Caso ao abrir sua _Pull Request_ apareça a mensagem _Can't automatically merge_, verifique se um novo código já foi mesclado na `master` entre o período que você finalizou suas alterações locais até o momento da abertura de solicitação do _Code Review_. Caso isso aconteça, você precisará atualizar seu código local e repetir a abertura da sua solicitação.
> - Para mais informações sobre repositórios `upstream`, `git pull`, `git push`, `git merge` e abertura de _Pull Requests_, consulte a Ajuda na nossa Wiki.

**Comment by RogerPhilippe** [comment]
Eu "tenho" interesse nessa tarefa.
RM 335720

**Comment by rafaelcaldastx** [comment]
Manifesto interesse nessa tarefa.
RM 336323

**Comment by FelipeMorato** [comment]
Temos interesse nesta issue.
RM 335676

**Comment by RogerPhilippe** [comment]
Boa tarde professor,

Estou com algumas dúvidas quanto a implementação da issue Criar Helper Bind com Padrão Proxy #35.
Não sei se estou conseguindo fazer corretamente, e fiquei em dúvida quanto ao Reflect.apply.
Segue:
Na FinanceController, adicionei a implementação para a classe Bind, como solicitado…

![duvida_controller](https://user-images.githubusercontent.com/17157253/79807175-87571c00-8340-11ea-9a1f-759059be09da.png)

Já a classe Bind, ficou assim:
![duvida_bind](https://user-images.githubusercontent.com/17157253/79807198-9f2ea000-8340-11ea-8e9f-4946052c5b8a.png)

Não sei se estou no caminho certo, se era para fazer assim... E não sei como aplicar Reflect.apply nesse contexto.
Você consegue nos ajudar?

**Comment by danvitoriano** [comment]
Oi @RogerPhilippe @rafaelcaldastx e @FelipeMorato, conseguem abrir um Pull Request dessa solução que chegaram? Assim consigo validar direto no código o que está certo ou o que precisa mudar. Obrigado!

**Comment by RogerPhilippe** [comment]
Boa tarde professor @danvitoriano, fiz a solicitação do pull como solicitado.

**Comment by danvitoriano** [comment]
obrigado @RogerPhilippe vou validar!

**Comment by danvitoriano** [comment]
resolvida com sucesso
