### ISSUE TITLE
💥 [OPEN SOURCE] - Persistência local no navegador com IndexedDB

### ISSUE THREAD

**Issue by danvitoriano** [danvitoriano/minhas-financas#36]
# Persistência local no navegador com IndexedDB

Um recurso interessante para persistência de dados é utilizar o armazenamento local direto no navegador. Nem todos sabem, mas os navegadores modernos possuem diversas opções para persistência no navegador do próprio usuário. Os mais conhecidos são o `local_storage` e a `session_storage`, que funcionam como uma memória local, podendo ser recuperada ao acessar o mesmo endereço a partir do mesmo navegador, ou ser apagada após o usuário fechar a sessão.

Outro banco de dados local poderoso oferecido pelos navegadores modernos como o Chrome é a API **IndexedDB**, um banco de dados que salva dados no formato objetos JavaScript.

Para aprofundar-se mais no assunto, consulte a documentação no MDN sobre IndexedDB:
https://developer.mozilla.org/pt-BR/docs/Web/API/IndexedDB_API/Usando_IndexedDB

Queremos persistir as finanças criadas no IndexedDB do navegador e listá-las ao iniciar a página no mesmo navegador. Para isso, você precisará adicionar algumas funcionalidades ao modelo da `ListaFinancas`.

Primeiro, é preciso criar um banco IndexedDB e uma conexão:

```js
this.connection;
this.indexedDb = "nome-do-banco";
this.openRequest = window.indexedDB.open(this.indexedDb, 1);
```

A instância de um banco IndexedDB recebe 3 funções principais:

```js
this.openRequest.onupgradeneeded = (e) => {
  let minhaConnection = e.target.result;
  if (minhaConnection.objectStoreNames.contains(this.indexedDb)) {
    minhaConnection.deleteObjectStore(this.indexedDb);
  }
  minhaConnection.createObjectStore(this.indexedDb, {
    autoIncrement: true,
  });
};
this.openRequest.onsuccess = (e) => {
  this.connection = e.target.result;
};
this.openRequest.onerror = (e) => {
  console.log(e.target.error);
  // faça algo com o erro
};
```

O método `adiciona`de `ListaFinanca`, além de adicionar uma finança, agora persistirá a mesma no IndexedDB local criado acima. É preciso antes abrir uma conexão com este banco e acessar a base de dados (**_store_**) para adicionar uma nova finança com o método `.add()`:

```js
let transaction = connection.transaction([this.indexedDb], "readwrite");
let store = transaction.objectStore(this.indexedDb);
// adicionar finança
```

Para testar a persistência no banco de dados, verifique a guia **Aplicativo** do navegador no **Modo Desenvolvedor**, e busque pelo nome do banco criado no item **IndexedDB**.

**Comment by fwfcunha** [comment]
Eu

**Comment by cunhaguilherme** [comment]
Tenho interesse!
Guilherme Cunha - RM 335526

**Comment by fwfcunha** [comment]
Filipe Cunha - RM335525

**Comment by asnisapps** [comment]
Me gusta!
Fabio Asnis - RM335694

**Comment by GAPvox** [comment]
Tenho interesse.
Gabriel André Piva - RM 335499

**Comment by danvitoriano** [comment]
estão precisando de ajuda nesta issue @cunhaguilherme @GAPvox @fwfcunha @asnisapps ?

**Comment by danvitoriano** [comment]
resolvida com sucesso
